const preloadables = {}
preloadables.images = [
  "logoWhite.webp",
  "paydayThumb.png",
  "images/blue.svg",
  "images/cape-bg.png",
  "images/green.svg",
  "images/ikea.svg",
  "images/master.png",
  "images/master__back.png",
  "images/master__back__m.png",
  "images/master__front.png",
  "images/master__front__m.png",
  "images/mockup.png",
  "images/nike.svg",
  "images/pad-1.png",
  "images/pad-2.png",
  "images/pad-3.png",
  "images/padl-1.png",
  "images/padl-2.png",
  "images/padl-3.png",
  "images/sephora.svg",
  "images/verve.png",
  "images/verve__back.png",
  "images/verve__back__m.png",
  "images/verve__front.png",
  "images/verve__front__m.png",
  "images/visa.png",
  "images/visa__back.png",
  "images/visa__back__m.png",
  "images/visa__front.png",
  "images/visa__front__m.png",
  "images/black.svg",
  "images/mall/nike-logo.png",
  "images/mall/nike-up.png",
  "images/mall/nike-left.png",
  "images/mall/nike-right.png",
  "images/mall/nike-down.png",
  "images/mall/ikea-logo.png",
  "images/mall/ikea-up.png",
  "images/mall/ikea-left.png",
  "images/mall/ikea-right.png",
  "images/mall/ikea-down.png",
  "images/mall/sephora-logo.png",
  "images/mall/sephora-up.png",
  "images/mall/sephora-left.png",
  "images/mall/sephora-right.png",
  "images/mall/sephora-down.png",
]
preloadables.videos = []
preloadables.textures = {}
preloadables.exports = {}

module.exports = preloadables
