const preloadables = {}
preloadables.images = [
  "logoWhite.webp",
  // "paydayThumb.webp",
  "images/blue.svg",
  "images/cape-bg.webp",
  "images/green.svg",
  // "images/ikea.svg",
  "images/master.webp",
  "images/master__back.webp",
  "images/master__back__m.webp",
  "images/master__front.webp",
  "images/master__front__m.webp",
  "images/mockup.webp",
  // "images/nike.svg",
  // "images/pad-1.webp",
  // "images/pad-2.webp",
  // "images/pad-3.webp",
  // "images/padl-1.webp",
  // "images/padl-2.webp",
  // "images/padl-3.webp",
  // "images/sephora.svg",
  "images/verve.webp",
  "images/verve__back.webp",
  "images/verve__back__m.webp",
  "images/verve__front.webp",
  "images/verve__front__m.webp",
  "images/visa.webp",
  "images/visa__back.webp",
  "images/visa__back__m.webp",
  "images/visa__front.webp",
  "images/visa__front__m.webp",
  "images/black.svg",
  "images/mall/nike-logo.webp",
  "images/mall/nike-up.webp",
  "images/mall/nike-left.webp",
  "images/mall/nike-right.webp",
  "images/mall/nike-down.webp",
  "images/mall/ikea-logo.webp",
  "images/mall/ikea-up.webp",
  "images/mall/ikea-left.webp",
  "images/mall/ikea-right.webp",
  "images/mall/ikea-down.webp",
  "images/mall/sephora-logo.webp",
  "images/mall/sephora-up.webp",
  "images/mall/sephora-left.webp",
  "images/mall/sephora-right.webp",
  "images/mall/sephora-down.webp",
]
preloadables.videos = []
preloadables.textures = {}
preloadables.exports = {}

module.exports = preloadables
